version: '3.8'

services:
  gateway:
    build: ./gateway
    image: shareit-gateway
    container_name: sh-gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      #- TZ=Europe/Moscow

  server:
    build: ./server
    image: shareit-server
    container_name: sh-server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      #- TZ=Europe/Moscow

  db:
    image: postgres:14.7-alpine
    container_name: shareit-db
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1